//
//  ListPresenter.swift
//  TabBarIGListKitMagic
//
//  Created by Michael Fekadu on 6/21/17.
//  Copyright (c) 2017 mikes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListPresenterInput
{
  func presentSomething(response: List.Something.Response)
}

protocol ListPresenterOutput: class
{
  func displaySomething(viewModel: List.Something.ViewModel)
}

class ListPresenter: ListPresenterInput
{
  weak var output: ListPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: List.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = List.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
