//
//  ListInteractor.swift
//  TabBarIGListKitMagic
//
//  Created by Michael Fekadu on 6/21/17.
//  Copyright (c) 2017 mikes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListInteractorInput
{
  func doSomething(request: List.Something.Request)
}

protocol ListInteractorOutput
{
  func presentSomething(response: List.Something.Response)
}

class ListInteractor: ListInteractorInput
{
  var output: ListInteractorOutput!
  var worker: ListWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: List.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ListWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = List.Something.Response()
    output.presentSomething(response: response)
  }
}
